name: foldable_list_ml
description: A foldable list package that provides maximum display configuration.
version: 0.1.0
homepage: https://github.com/Morlinnn/foldable_list_ml

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: